package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import util.clsConexao;
import util.clsImagem;

/**
 *
 * @author Caio ETESP
 */
public class Cadastrar extends javax.swing.JFrame {
    
    private String caminhoImagem;
    
    public Cadastrar() {
        initComponents();
        SampleMoneyFormat(ftxtPreco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagem = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ftxtPreco = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRemoverImagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROVA DE JAVA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setText("Imagem");
        lblImagem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagemMouseClicked(evt);
            }
        });
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 88, 105));

        btnCadastrar.setText("Incluir");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));
        getContentPane().add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 200, -1));
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 40, -1));

        jLabel2.setText("Marca");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel3.setText("Produto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel4.setText("Quantidade");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel5.setText("Preço unitário");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));
        getContentPane().add(ftxtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 60, -1));

        jLabel1.setText("CRUD JAVA 0.1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btnRemoverImagem.setText("Remover");
        btnRemoverImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverImagemActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoverImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        setSize(new java.awt.Dimension(410, 271));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseClicked
        caminhoImagem = new clsImagem().openDialogAndLoadImageSelectedToLabel(lblImagem);          
    }//GEN-LAST:event_lblImagemMouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if(txtMarca.getText().equals("") || txtProduto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nao pode ficar campos vazio");  
            return;
        }
        
        String strSalario = ftxtPreco.getText().replaceAll("\\.", "").replace(",", ".");
        Double salario = strSalario.equals("") ? 0 : Double.parseDouble(strSalario);

        try {
            Connection con =  new clsConexao().getConnection();
            //adicionando os parametros
            try (PreparedStatement pstmt = con.prepareStatement("insert into tbl_Produto  VALUES (?, ?, ?, ?, ?)") //values ('marca', 'produto', 3, 1230.0, 'abc')
            ) {
                //adicionando os parametros
                pstmt.setString(1, txtMarca.getText());
                pstmt.setString(2, txtProduto.getText());
                pstmt.setObject(3, txtQuantidade.getText()); //pstmt.setString(3, "24/05/1996");
                pstmt.setDouble(4, salario);
                if(lblImagem.getIcon() != null) {
                    pstmt.setString(5, caminhoImagem);
                }else
                    pstmt.setNull(5, java.sql.Types.VARCHAR);
                pstmt.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Inserindo com Sucesso");
            limparCampos();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        new Consultar().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnRemoverImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverImagemActionPerformed
        caminhoImagem = null;
        lblImagem.setIcon(null);
    }//GEN-LAST:event_btnRemoverImagemActionPerformed

    private void limparCampos()
    {
        txtMarca.setText("");
        txtProduto.setText("");
        txtQuantidade.setText("");
        ftxtPreco.setText("0");
        lblImagem.setIcon(null);
        caminhoImagem = null;
    }
    
    public static void SampleMoneyFormat(javax.swing.JFormattedTextField jFormattedTextField)
    {
        DecimalFormat dFormat = new DecimalFormat("#,###,###.00") ;
        NumberFormatter formatter = new NumberFormatter(dFormat) ;
        formatter.setFormat(dFormat) ;
        formatter.setAllowsInvalid(false); 
        jFormattedTextField.setFormatterFactory(new DefaultFormatterFactory(formatter));
        
        //example set double value
        //textField.setText(new DecimalFormat("#,##0.00").format(4444.5));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRemoverImagem;
    private javax.swing.JFormattedTextField ftxtPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
