/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.Cadastrar;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import util.clsConexao;
import util.clsImagem;

/**
 *
 * @author ETESP
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Consultar
     */
    
    ResultSet rs = null;
    Integer id;
    String foto;
    
    public Consultar() {
        initComponents();
        Cadastrar.SampleMoneyFormat(ftxtPreco);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagem = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnGerarRelatorio = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        ftxtPreco = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRemoverImagem = new javax.swing.JButton();
        lblNumeroRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setText("imagem");
        lblImagem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagemMouseClicked(evt);
            }
        });
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 88, 105));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerarRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, -1));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));
        getContentPane().add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 200, -1));
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, -1));

        jLabel2.setText("Marca");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel3.setText("Produto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel4.setText("Quantidade");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel5.setText("Preço unitário");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsDeBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        btnEnd.setText(">>");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsDeBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsDeBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsDeBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));
        getContentPane().add(ftxtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 80, -1));

        jLabel1.setText("CRUD JAVA 0.1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 20));

        btnRemoverImagem.setText("remover");
        btnRemoverImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverImagemActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoverImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        lblNumeroRegistro.setText("n");
        getContentPane().add(lblNumeroRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 40, 20));

        setSize(new java.awt.Dimension(409, 303));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CarregarResultSet();
    }//GEN-LAST:event_formWindowOpened

    private void btnsDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsDeBuscaActionPerformed
        javax.swing.JButton btnClicked = (javax.swing.JButton) evt.getSource();
        
        try {
            boolean foi = false;
            if(btnClicked == btnNext) //  >
                foi = rs.next();
            else if(btnClicked == btnBack)//  <
                foi = rs.previous();
            else if(btnClicked == btnFirst)//  <<
                foi = rs.first();
            else if (btnClicked == btnEnd)//  >>
                foi = rs.last();
            
            if(foi)
                ExibirDados();                   
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());            
        }
    }//GEN-LAST:event_btnsDeBuscaActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(txtMarca.getText().equals("") || txtProduto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nao pode ficar campos vazio");         
            return;
        }
        String strSalario = ftxtPreco.getText().replaceAll("\\.", "").replace(",", ".").replace("R$", "");
        Double salario = strSalario.equals("") ? 0 : Double.parseDouble(strSalario);
        
        try {
            Connection con =  new clsConexao().getConnection();
            
            try (PreparedStatement pstmt = con.prepareStatement("update tbl_Produto set marca = ?, produto = ?, quantidade = ?, preco = ?, caminho = ? where id = "+id)) {
                pstmt.setString(1, txtMarca.getText());
                pstmt.setString(2, txtProduto.getText());
                pstmt.setObject(3, txtQuantidade.getText()); //pstmt.setString(3, "24/05/1996");
                pstmt.setDouble(4, salario);
                if(lblImagem.getIcon() != null)
                    pstmt.setString(5, foto);
                else
                    pstmt.setNull(5, java.sql.Types.VARCHAR);
                pstmt.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Alterado com Sucesso");
            CarregarResultSet();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseClicked
        foto = new clsImagem().openDialogAndLoadImageSelectedToLabel(lblImagem); 
    }//GEN-LAST:event_lblImagemMouseClicked

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed

        try {
            FileWriter out = new FileWriter("c:/Relatorio.html");
            out.write("<html><body><center><br>");
            out.write("<table border=2>");
            out.write("<tr><td colspan='4'>");
            out.write("Produtos");
            out.write("</td></tr>");
            out.write("<tr>");
            out.write("<td>Marca</td>");            
            out.write("<td>Produto</td>");                    
            out.write("<td>Quantidade</td>");                    
            out.write("<td>Preco</td>");
            out.write("</tr>");
            out.write("<tr>");
            
            try {
                rs.beforeFirst();
                while(rs.next())
                {
                    out.write("<td>"+rs.getString("marca")+"</td>");
                    out.write("<td>"+rs.getString("produto")+"</td>");
                    out.write("<td>"+rs.getString("quantidade")+"</td>");
                    out.write("<td>"+NumberFormat.getCurrencyInstance(new Locale("pt", "BR")).format(rs.getDouble("preco"))+"</td>");
                    out.write("</tr>");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            out.write("</table></center></body></html>");
            out.close();
        }catch (IOException e) {
            e.printStackTrace();
        }
        
        File html = new File("c:/Relatorio.html");
        try{
            Desktop.getDesktop().open(html);
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showConfirmDialog(null, "Falha no arquivo");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        
        try (Statement stmt = new clsConexao().getConnection().createStatement()) {
            stmt.executeUpdate("DELETE from tbl_Produto where id = "+id);
            stmt.close();
            JOptionPane.showMessageDialog(null, "Excluido com Sucesso");            
            CarregarResultSet();
            limparCampos();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnRemoverImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverImagemActionPerformed
        foto = null;
        lblImagem.setIcon(null);
    }//GEN-LAST:event_btnRemoverImagemActionPerformed
    
    private void CarregarResultSet()
    {
        try {
            Connection con =  new clsConexao().getConnection();            
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stmt.executeQuery("select * from tbl_Produto");
            //PreparedStatement pstmt = con.prepareStatement("select * from tbl_Produto"); //"SELECT * FROM Pessoa WHERE Nome Like ?"
            //rs = pstmt.executeQuery();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }   
    }
    
    private void ExibirDados()
    {
        limparCampos();
        try {
            id = rs.getInt(1);
            txtMarca.setText(rs.getString(2));
            txtProduto.setText(rs.getString(3));
            txtQuantidade.setText(rs.getString(4));
            ftxtPreco.setText(new DecimalFormat("#,##0.00").format(rs.getDouble(5)));
        
            lblNumeroRegistro.setText(String.valueOf(rs.getRow())); 
            String caminhoFoto = rs.getString(6);
            if(caminhoFoto != null) {
                new clsImagem().loadImageToLabel(lblImagem, caminhoFoto);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }        
    }
    
    private void limparCampos()
    {
        id = 0;
        foto = null;
        txtMarca.setText("");
        txtProduto.setText("");
        txtQuantidade.setText("");
        ftxtPreco.setText(null);
        lblImagem.setIcon(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRemoverImagem;
    private javax.swing.JFormattedTextField ftxtPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNumeroRegistro;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
